import type { MetadataRoute } from "next";

/**
 * The web app manifest, which is what makes "Add to Home Screen" produce
 * something that looks like an app rather than a browser bookmark.
 *
 * Icons are generated by `npm run icons` from assets/logo.png - see
 * scripts/build-icons.ts. The maskable one is separate and padded on purpose:
 * Android crops adaptive icons to a circle or squircle and would otherwise
 * slice the speech bubbles off the artwork.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "1 Percent More Fluent",
    // Home screens truncate at roughly twelve characters, and "1 Percent More
    // Fluent" would come back as "1 Percent M...".
    short_name: "Fluent",
    description:
      "Short stories, articles and conversations in the language you are learning, at a level you can actually read.",
    start_url: "/",
    // Standalone rather than fullscreen: this is a reading app, and hiding the
    // status bar would take the clock and the battery with it.
    display: "standalone",
    // --background from globals.css. background_color is what fills the screen
    // while the app is starting, so a mismatch here shows as a flash.
    background_color: "#faf8f5",
    theme_color: "#faf8f5",
    orientation: "portrait",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
