/**
 * Assert the Chinese placement test is built on HSK 3.0 and stays graded.
 *
 *   npx tsx scripts/check-hsk.ts
 *
 * No LLM, no network: everything here reads the committed placement.json. That
 * file is generated by `npm run hsk`, and generated data is exactly the kind
 * that rots silently - a rebuild that quietly drops the top band or shuffles
 * every pool is invisible in review and obvious to a reader taking the test.
 *
 * The assertion that matters most is the graded one. The whole reason this data
 * exists is that the previous test could not be failed: its hardest band was
 * ranks 11,001-20,000 of a subtitle corpus, which held 不便, 安好, 指头 and
 * 往日 - four ordinary words standing in for nine thousand. Everyone reached
 * the top of the scale, which is why the app was telling its owner he knew
 * twenty thousand words.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { simplifiedChinese } from "../src/lib/languages/zh-CN";

let failures = 0;

function check(name: string, actual: unknown, expected: unknown) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  const pass = a === e;
  if (!pass) failures++;
  console.log(`${pass ? "ok  " : "FAIL"} ${name}`);
  if (!pass) console.log(`       expected ${e}\n       got      ${a}`);
}

function ok(name: string, condition: boolean, detail = "") {
  if (!condition) failures++;
  console.log(`${condition ? "ok  " : "FAIL"} ${name}${detail ? `  ${detail}` : ""}`);
}

interface Band {
  level: string;
  minRank: number;
  maxRank: number;
  words: string[];
  pseudowords: string[];
}

const data = JSON.parse(
  readFileSync(join(process.cwd(), "src", "data", "zh-CN", "placement.json"), "utf8"),
) as { source?: string; bands: Band[] };

console.log("--- the data says where it came from ---");
{
  // The MIT licence this data arrives under requires the notice to travel with
  // it. A generated file that loses its provenance line is how attribution
  // quietly disappears.
  ok("the file names its source", /ivankra\/hsk30/.test(data.source ?? ""), data.source ?? "(none)");
  ok("...and the standard behind it", /GF 0025-2021/.test(data.source ?? ""));
  ok("...and points at the notice", /NOTICE/.test(data.source ?? ""));
}

console.log();
console.log("--- the bands are HSK levels, in order ---");
{
  check(
    "every level of the standard is present, with 7-9 split",
    data.bands.map((b) => b.level),
    ["1", "2", "3", "4", "5", "6", "7-9a", "7-9b"],
  );

  // Contiguous and ascending: the scorer credits a band by its WIDTH, so a gap
  // or an overlap silently mis-sizes the estimate rather than throwing.
  let previous = 0;
  let contiguous = true;
  for (const b of data.bands) {
    if (b.minRank !== previous + 1 || b.maxRank < b.minRank) contiguous = false;
    previous = b.maxRank;
  }
  ok("cumulative positions run end to end with no gaps", contiguous);
  ok(
    "the list is about the size the standard publishes",
    previous > 10_500 && previous <= 11_092,
    `${previous} of 11,092`,
  );

  // HSK 1 is 500 words and 7-9 is 5,636. Splitting the top band in two still
  // leaves each half wider than any single lower band, but no longer five times
  // wider than all of them together.
  const widths = data.bands.map((b) => b.maxRank - b.minRank + 1);
  ok(
    "no band is more than a third of the whole list",
    Math.max(...widths) < previous / 3,
    `widest ${Math.max(...widths)}`,
  );
}

console.log();
console.log("--- every band can actually be answered ---");
{
  for (const b of data.bands) {
    ok(`HSK ${b.level} offers a real pool`, b.words.length >= 8, `${b.words.length} words`);
    ok(`HSK ${b.level} brings its own catch trials`, b.pseudowords.length >= 2,
      `${b.pseudowords.length} pseudowords`);
  }
  // The old top band had four. Five per band are drawn at test time, so a pool
  // of four means the hardest band showed fewer items than any other - the one
  // place resolution was already worst.
  const smallest = Math.min(...data.bands.map((b) => b.words.length));
  ok("no band is thinner than the sample drawn from it", smallest >= 5, `${smallest}`);
}

console.log();
console.log("--- nothing appears twice ---");
{
  const all = data.bands.flatMap((b) => b.words);
  check("no word is offered in two bands", all.length - new Set(all).size, 0);
  const fake = data.bands.flatMap((b) => b.pseudowords);
  check("no pseudoword is either", fake.length - new Set(fake).size, 0);
  // A pseudoword that is secretly a real word turns a catch trial into a
  // penalty for knowing something.
  const real = new Set(all);
  ok("and no pseudoword is a real HSK word", fake.every((w) => !real.has(w)));
}

console.log();
console.log("--- the test is graded, which is the whole point ---");
{
  // Every item is Han characters only. The subtitle-derived list leaked Latin
  // text and proper nouns into the bands; a curated standard should not.
  const all = data.bands.flatMap((b) => b.words);
  ok("every item is Chinese", all.every((w) => /^[一-鿿]+$/.test(w)));

  // 成语 are part of HSK 7-9, and they are why the top band is worth
  // answering. They sort into the rarer half because film dialogue rarely uses
  // them - see SPLIT_LAST in build-hsk.ts.
  const top = data.bands.at(-1)!;
  const fourChar = top.words.filter((w) => w.length === 4);
  ok(
    "the hardest band reaches four-character set phrases",
    fourChar.length > 0,
    fourChar.join(", ") || "none",
  );

  // The direction that matters: later bands must not be full of shorter, more
  // basic items than earlier ones. Average length is a crude proxy and a real
  // one - HSK 1 is 错/坏/用, HSK 7-9b is 舆论/纵观/不得而知.
  const meanLength = (b: Band) =>
    b.words.reduce((n, w) => n + w.length, 0) / b.words.length;
  ok(
    "the hardest band's items are longer than the easiest band's",
    meanLength(data.bands.at(-1)!) > meanLength(data.bands[0]!),
    `${meanLength(data.bands.at(-1)!).toFixed(2)} vs ${meanLength(data.bands[0]!).toFixed(2)}`,
  );
}

console.log();
console.log("--- the labels match the standard ---");
{
  const label = (n: number) => simplifiedChinese.levelLabel(n);
  check("500 words is still working through HSK 2", label(500), "HSK 2");
  check("just under is HSK 1", label(499), "HSK 1");
  check("the HSK 4/5 boundary is the standard's 3,245", label(3_245), "HSK 5");
  check("...and one short of it is not", label(3_244), "HSK 4");
  check("the top band is named as the standard names it", label(9_000), "HSK 7-9");
  // The old thresholds put this boundary at 5,500 and called everything up to
  // 11,000 "HSK 6", which was two bands' worth under one name.
  check("HSK 6 ends where the standard ends it", label(5_456), "HSK 7-9");
}

console.log();
if (failures > 0) {
  console.log(`${failures} failing`);
  process.exit(1);
}
console.log("all HSK checks passed");
