/**
 * Is the generated text actually CORRECT language? One measurement.
 *
 *   npx tsx scripts/judge-correctness.ts          # dry run: what would be judged, and the cost
 *   npx tsx scripts/judge-correctness.ts --run    # spend
 *
 * The difficulty verifier checks how HARD a piece is; nothing has ever checked
 * whether it is right. That is the one failure mode a learner cannot detect -
 * an unidiomatic phrase served to somebody who cannot yet tell teaches wrong
 * language, silently, and no lookup rate or quiz score would ever surface it.
 * This app has a rule about unmeasured things, and until now this was one.
 *
 * JUDGED BY A DIFFERENT LAB. Every stored piece so far was generated by Google
 * or OpenAI models; the judge is pinned to Anthropic, because a model grading
 * its own family's output shares its family's blind spots. The script refuses
 * to run if the chain resolves to anything but the judge, same pattern as
 * bench-difficulty.ts - a fallback mid-run must not silently change who is
 * grading.
 *
 * WHAT COUNTS AS AN ERROR. The judge is told to ignore simplicity and style -
 * the text is deliberately simple, and "this reads like a textbook" is the
 * product working. Only things a native speaker would call wrong: grammar,
 * wrong word, phrasing no native would produce.
 *
 * COST. ~1.5k tokens in + ~300 out per piece on claude-haiku-4-5 ($1/$5 per
 * MTok): about half a cent per piece, printed exactly in the dry run.
 */
import { readFileSync } from "node:fs";
import { z } from "zod";

function loadEnv() {
  try {
    for (const line of readFileSync(".env.local", "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && process.env[m[1]!] === undefined) process.env[m[1]!] = m[2]!;
    }
  } catch {
    // No .env.local is fine if the key is exported.
  }
}

const JUDGE = process.env.JUDGE_MODEL ?? "anthropic:claude-haiku-4-5";
const PER_LANGUAGE = Number(process.env.JUDGE_SAMPLES ?? 8);

const VERDICT = z.object({
  errors: z
    .array(
      z.object({
        quote: z.string().describe("The exact problematic phrase, quoted from the text."),
        problem: z.string().describe("What is wrong, in one short English sentence."),
        severity: z
          .enum(["minor", "serious"])
          .describe(
            "serious = teaches wrong language (grammar error, wrong word, phrasing no native would produce); minor = understandable but slightly off.",
          ),
      }),
    )
    .describe("Genuine language errors only. Empty if the text is clean."),
  verdict: z
    .enum(["natural", "acceptable", "problematic"])
    .describe(
      "natural = a native editor would pass it; acceptable = minor blemishes only; problematic = contains something that teaches wrong language.",
    ),
});

interface PieceRow {
  id: string;
  language: string;
  title: string;
  body: string;
  model: string;
}

async function main() {
  const run = process.argv.includes("--run");

  const { getDb } = await import("../src/server/db");
  const rows = (
    getDb()
      .prepare(
        // Newest first so the sample reflects the CURRENT prompt and chain,
        // not the app's archaeology.
        `SELECT id, language, title, body, model FROM pieces ORDER BY created_at DESC`,
      )
      .all() as PieceRow[]
  ).filter((row) =>
    // A length floor keeps two-line fixtures out - but it has to be
    // per-script, not per-byte: 400 characters of Chinese is a whole article
    // while 400 of Spanish is two sentences, and a shared floor would quietly
    // exclude every Chinese piece from the sample.
    row.language.startsWith("zh") ? row.body.length > 150 : row.body.length > 400,
  );

  const byLanguage = new Map<string, PieceRow[]>();
  for (const row of rows) {
    const list = byLanguage.get(row.language) ?? [];
    if (list.length < PER_LANGUAGE) {
      list.push(row);
      byLanguage.set(row.language, list);
    }
  }
  const sample = [...byLanguage.values()].flat();

  const chars = sample.reduce((n, p) => n + p.body.length, 0);
  // Rough token arithmetic for the dry run: chars/3.5 in + ~300 out per piece.
  const inTokens = Math.round(chars / 3.5) + sample.length * 250;
  const outTokens = sample.length * 300;
  const usd = (inTokens / 1e6) * 1 + (outTokens / 1e6) * 5;

  console.log(`judge     ${JUDGE}   (pinned - refuses to run on any other chain)`);
  console.log(
    `sample    ${sample.length} pieces (${[...byLanguage.entries()]
      .map(([l, ps]) => `${l}: ${ps.length}`)
      .join(", ")}), newest first, fixtures excluded by a per-language length floor`,
  );
  console.log(`estimate  ~${inTokens.toLocaleString("en")} in + ~${outTokens.toLocaleString("en")} out tokens  ≈ $${usd.toFixed(2)}`);
  if (!run) {
    console.log("\nDry run. Nothing was judged. Add --run to spend.");
    return;
  }

  loadEnv();
  process.env.LLM_MODELS = JUDGE;
  const { generateStructured, getConfiguredChain } = await import("../src/server/llm");

  const chain = getConfiguredChain();
  if (chain.length !== 1 || `${chain[0]!.provider}:${chain[0]!.id}` !== JUDGE) {
    console.error(`refusing to run: chain is ${chain.map((c) => `${c.provider}:${c.id}`).join(", ")}`);
    process.exit(1);
  }

  const { getLanguage } = await import("../src/lib/languages");

  const results: {
    piece: PieceRow;
    verdict: z.infer<typeof VERDICT>;
  }[] = [];
  let stopped = "";

  for (const piece of sample) {
    const languageName = getLanguage(piece.language).name;
    const paragraphs = (JSON.parse(piece.body) as string[]).join("\n\n");
    try {
      const { object } = await generateStructured({
        op: "judge-correctness",
        schema: VERDICT,
        system:
          `You are a native ${languageName} editor reviewing text written for language learners. ` +
          `The text is DELIBERATELY simple - short sentences, common words, a restricted grammar. ` +
          `Simplicity is not an error. Report only things a native speaker would call WRONG: ` +
          `grammar mistakes, wrong word choice, or phrasing no native would ever produce. ` +
          `If the text is simple but correct, say it is natural and report nothing.`,
        prompt: paragraphs,
        temperature: 0,
      });
      results.push({ piece, verdict: object });
      process.stdout.write(
        object.verdict === "natural" ? "." : object.verdict === "acceptable" ? "o" : "X",
      );
    } catch (err) {
      stopped = err instanceof Error ? err.message : String(err);
      break;
    }
  }
  console.log("\n");

  if (stopped) console.log(`stopped early: ${stopped.slice(0, 200)}\n`);

  // --- the report -----------------------------------------------------------
  for (const [lang, pieces] of byLanguage) {
    const judged = results.filter((r) => r.piece.language === lang);
    if (!judged.length) continue;
    const serious = judged.flatMap((r) =>
      r.verdict.errors.filter((e) => e.severity === "serious").map((e) => ({ r, e })),
    );
    const minor = judged.flatMap((r) => r.verdict.errors.filter((e) => e.severity === "minor"));
    console.log(`=== ${lang}  (${judged.length}/${pieces.length} judged) ===`);
    for (const v of ["natural", "acceptable", "problematic"] as const) {
      const n = judged.filter((r) => r.verdict.verdict === v).length;
      console.log(`  ${v.padEnd(12)} ${n}`);
    }
    console.log(`  serious errors ${serious.length}, minor ${minor.length}`);
    for (const { r, e } of serious) {
      console.log(`   ! [${r.piece.title}] "${e.quote}" - ${e.problem}`);
      console.log(`     generated by ${r.piece.model}`);
    }
    console.log("");
  }

  const problematic = results.filter((r) => r.verdict.verdict === "problematic").length;
  console.log(
    `${results.length} judged, ${problematic} problematic. ` +
      (problematic === 0
        ? "No evidence the app is teaching wrong language, at this sample size."
        : "The serious errors above are the ones a learner cannot detect - read them."),
  );
}

void main();
