/**
 * Are the GLOSSES right? One measurement.
 *
 *   npx tsx scripts/judge-glossary.ts          # dry run: what would be judged, and the cost
 *   npx tsx scripts/judge-glossary.ts --run    # spend
 *
 * Sibling to judge-correctness.ts, which asks whether the generated TEXT is
 * correct language. Nothing has ever asked whether the definitions attached to
 * it are correct - and a gloss is the one thing in this app that teaches a
 * meaning DIRECTLY. A wrong piece of prose might still be understood; a wrong
 * gloss is simply learned. It is also undetectable by the reader, who tapped
 * the word precisely because they did not know it.
 *
 * TWO SOURCES, AND THE SECOND IS THE INTERESTING ONE.
 *
 *   piece    The glossary the generating model attached to a piece. Judged
 *            against the sentence it actually appears in, so this measures
 *            plain correctness.
 *
 *   cache    gloss_cache, which is keyed (language, word) with NO context
 *            stored, while the gloss that filled it was written FROM a
 *            context. So one sense gets frozen and served to every later
 *            reader. This sample judges each cached meaning against real
 *            occurrences in OTHER pieces - which is the only way to find out
 *            whether that design costs anything in practice.
 *
 * The verdict separates the two failure modes deliberately:
 *
 *   correct      the meaning fits this use
 *   wrong-sense  a real meaning of the word, but not the one used here
 *   wrong        not a meaning of the word at all
 *
 * `wrong-sense` is the whole reason this script exists. `red` is cached as
 * "fishing net" - true where it was first tapped, useless in a piece about
 * networks. Counting those tells us whether the context-free cache needs
 * changing or is a theoretical worry that never fires.
 *
 * JUDGED BY A DIFFERENT LAB, same rule as judge-correctness.ts. Every stored
 * piece was generated by a Gemini model, so the glosses are Gemini's; the
 * judge is pinned to Anthropic and the script refuses to run if a fallback
 * would change who is grading.
 */
import { readFileSync } from "node:fs";
import { z } from "zod";

function loadEnv() {
  try {
    for (const line of readFileSync(".env.local", "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && process.env[m[1]!] === undefined) process.env[m[1]!] = m[2]!;
    }
  } catch {
    // No .env.local is fine if the key is exported.
  }
}

const JUDGE = process.env.JUDGE_MODEL ?? "anthropic:claude-haiku-4-5";
/** Items per language, per source. Both sources are sampled independently. */
const PER_LANGUAGE = Number(process.env.JUDGE_SAMPLES ?? 12);

const VERDICT = z.object({
  fits: z
    .enum(["correct", "wrong-sense", "wrong"])
    .describe(
      "correct = the definition fits the word AS USED in this sentence; " +
        "wrong-sense = the definition is a genuine meaning of the word but NOT the meaning used here; " +
        "wrong = not a meaning of this word at all, or plainly mistaken.",
    ),
  better: z
    .string()
    .describe(
      "If not correct, the short definition that SHOULD have been given for this use. Empty string if correct.",
    ),
  note: z.string().describe("One short English sentence explaining the call. Empty if correct."),
});

interface PieceRow {
  id: string;
  language: string;
  title: string;
  body: string;
  glossary: string;
  model: string;
}

interface CacheRow {
  language: string;
  word: string;
  meaning: string;
}

interface Item {
  source: "piece" | "cache";
  language: string;
  word: string;
  meaning: string;
  sentence: string;
  /** For cache items: how many distinct pieces this word occurs in. */
  spread: number;
  where: string;
}

/** gloss_cache.meaning holds JSON, and two shapes of it - 199 rows are
 *  {meaning}, 15 older ones also carry {lemma, partOfSpeech}. */
function plainMeaning(raw: string): string {
  try {
    const parsed = JSON.parse(raw) as { meaning?: string };
    if (parsed && typeof parsed.meaning === "string") return parsed.meaning;
  } catch {
    // Older rows may be bare strings.
  }
  return raw;
}

async function main() {
  const run = process.argv.includes("--run");

  const { getDb } = await import("../src/server/db");
  const { getLanguage } = await import("../src/lib/languages");

  /**
   * Does this sentence really contain this word?
   *
   * The answer is not the same in every script, and getting it wrong in either
   * direction was measured on this corpus.
   *
   * Latin script needs WHOLE TOKENS. The first version used
   * `sentence.includes(word)`, and "oso" matched inside "famosos" - so the
   * judge was handed a bear gloss against a sentence about museums and,
   * correctly, called it nonsense. A false occurrence yields a real-looking
   * verdict, which is the worst kind of measurement bug.
   *
   * Chinese needs the OPPOSITE. It has no word boundaries to respect, and the
   * segmenter groups longer units than a reader taps: 停 genuinely occurs in
   * 停下来, 账号 in 银行账号. Token equality rejected all 7 such cached words in
   * the corpus - every one a real occurrence. There the character span IS the
   * match, which is the same reasoning as the per-script length floor in
   * judge-correctness.ts.
   *
   * Multi-word selections (a swept phrase like "malas hierbas") have no single
   * token to match either, so those fall back to substring too - the
   * false-positive risk that motivated this function does not apply at phrase
   * length.
   */
  const occursIn = (sentence: string, word: string, code: string): boolean => {
    const target = word.trim();
    if (!target) return false;
    if (code.startsWith("zh")) return sentence.includes(target);
    if (/\s/.test(target)) return sentence.toLowerCase().includes(target.toLowerCase());
    return getLanguage(code)
      .words(sentence)
      .some((w) => w.toLowerCase() === target.toLowerCase());
  };

  const pieces = getDb()
    .prepare(`SELECT id, language, title, body, glossary, model FROM pieces ORDER BY created_at DESC`)
    .all() as PieceRow[];

  /** Every sentence of every piece, per language, with the piece it came from. */
  const sentencesFor = new Map<string, { pieceId: string; title: string; sentence: string }[]>();
  for (const piece of pieces) {
    const list = sentencesFor.get(piece.language) ?? [];
    let paragraphs: string[] = [];
    try {
      paragraphs = JSON.parse(piece.body) as string[];
    } catch {
      continue;
    }
    const language = getLanguage(piece.language);
    for (const paragraph of paragraphs) {
      for (const sentence of language.sentences(paragraph)) {
        const trimmed = sentence.trim();
        if (trimmed) list.push({ pieceId: piece.id, title: piece.title, sentence: trimmed });
      }
    }
    sentencesFor.set(piece.language, list);
  }

  const items: Item[] = [];

  // --- source 1: the glossary the model attached to its own piece -----------
  const pieceCount = new Map<string, number>();
  for (const piece of pieces) {
    let entries: { word: string; meaning: string }[] = [];
    try {
      entries = JSON.parse(piece.glossary) as { word: string; meaning: string }[];
    } catch {
      continue;
    }
    const language = getLanguage(piece.language);
    let paragraphs: string[] = [];
    try {
      paragraphs = JSON.parse(piece.body) as string[];
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (!entry?.word || !entry?.meaning) continue;
      if ((pieceCount.get(piece.language) ?? 0) >= PER_LANGUAGE) break;
      // The sentence it actually appears in, inside its OWN piece.
      let found = "";
      for (const paragraph of paragraphs) {
        for (const sentence of language.sentences(paragraph)) {
          if (occursIn(sentence, entry.word, piece.language)) {
            found = sentence.trim();
            break;
          }
        }
        if (found) break;
      }
      if (!found) continue; // A glossed word absent from its own text is a different bug.
      items.push({
        source: "piece",
        language: piece.language,
        word: entry.word,
        meaning: entry.meaning,
        sentence: found,
        spread: 1,
        where: piece.title,
      });
      pieceCount.set(piece.language, (pieceCount.get(piece.language) ?? 0) + 1);
    }
  }

  // --- source 2: one cached meaning, met in a DIFFERENT piece ---------------
  const cache = getDb()
    .prepare(`SELECT language, word, meaning FROM gloss_cache ORDER BY created_at DESC`)
    .all() as CacheRow[];

  const cacheCandidates: Item[] = [];
  for (const row of cache) {
    const all = sentencesFor.get(row.language) ?? [];
    const hits = all.filter((s) => occursIn(s.sentence, row.word, row.language));
    if (!hits.length) continue;
    const distinctPieces = new Set(hits.map((h) => h.pieceId)).size;
    // The last occurrence is the one least likely to be the context the gloss
    // was written from, which is exactly the case worth testing.
    const hit = hits[hits.length - 1]!;
    cacheCandidates.push({
      source: "cache",
      language: row.language,
      word: row.word,
      meaning: plainMeaning(row.meaning),
      sentence: hit.sentence,
      spread: distinctPieces,
      where: hit.title,
    });
  }
  // Words living in several pieces first: one frozen sense has to serve them all.
  cacheCandidates.sort((a, b) => b.spread - a.spread);
  const cacheCount = new Map<string, number>();
  for (const candidate of cacheCandidates) {
    if ((cacheCount.get(candidate.language) ?? 0) >= PER_LANGUAGE) continue;
    items.push(candidate);
    cacheCount.set(candidate.language, (cacheCount.get(candidate.language) ?? 0) + 1);
  }

  // --- dry run --------------------------------------------------------------
  const byKey = (source: string) => items.filter((i) => i.source === source);
  const chars = items.reduce((n, i) => n + i.sentence.length + i.meaning.length + i.word.length, 0);
  const inTokens = Math.round(chars / 3.5) + items.length * 150;
  const outTokens = items.length * 90;
  const usd = (inTokens / 1e6) * 1 + (outTokens / 1e6) * 5;

  const langs = [...new Set(items.map((i) => i.language))];
  console.log(`judge     ${JUDGE}   (pinned - refuses to run on any other chain)`);
  console.log(
    `sample    ${items.length} glosses - ${byKey("piece").length} from piece glossaries, ` +
      `${byKey("cache").length} from gloss_cache, up to ${PER_LANGUAGE} per language per source`,
  );
  for (const lang of langs) {
    const mine = items.filter((i) => i.language === lang);
    const multi = mine.filter((i) => i.source === "cache" && i.spread > 1).length;
    console.log(
      `          ${lang}: ${mine.length} (${mine.filter((i) => i.source === "piece").length} piece, ` +
        `${mine.filter((i) => i.source === "cache").length} cache, of which ${multi} occur in >1 piece)`,
    );
  }
  console.log(
    `estimate  ~${inTokens.toLocaleString("en")} in + ~${outTokens.toLocaleString("en")} out tokens  ≈ $${usd.toFixed(3)}`,
  );
  if (!run) {
    console.log("\nDry run. Nothing was judged. Add --run to spend.");
    return;
  }

  // --- spend ----------------------------------------------------------------
  loadEnv();
  process.env.LLM_MODELS = JUDGE;
  const { generateStructured, getConfiguredChain } = await import("../src/server/llm");

  const chain = getConfiguredChain();
  if (chain.length !== 1 || `${chain[0]!.provider}:${chain[0]!.id}` !== JUDGE) {
    console.error(`refusing to run: chain is ${chain.map((c) => `${c.provider}:${c.id}`).join(", ")}`);
    process.exit(1);
  }

  const results: { item: Item; verdict: z.infer<typeof VERDICT> }[] = [];
  let stopped = "";

  for (const item of items) {
    const languageName = getLanguage(item.language).name;
    try {
      const { object } = await generateStructured({
        op: "judge-glossary",
        schema: VERDICT,
        system:
          `You are a bilingual ${languageName}-English lexicographer checking definitions written ` +
          `for language learners. You are given a ${languageName} word, the English definition the ` +
          `app showed for it, and the sentence the reader met it in. Decide whether that definition ` +
          `is right FOR THAT USE. Be strict about sense: a definition can be a perfectly good ` +
          `dictionary entry for the word and still be the wrong sense for this sentence, and that ` +
          `is the case you must catch. Terse definitions are fine - brevity is not an error.`,
        prompt:
          `Word: ${item.word}\n` +
          `Definition shown to the reader: ${item.meaning}\n` +
          `Sentence it appeared in: ${item.sentence}`,
        temperature: 0,
      });
      results.push({ item, verdict: object });
      process.stdout.write(
        object.fits === "correct" ? "." : object.fits === "wrong-sense" ? "s" : "X",
      );
    } catch (err) {
      stopped = err instanceof Error ? err.message : String(err);
      break;
    }
  }
  console.log("\n");
  if (stopped) console.log(`stopped early: ${stopped.slice(0, 200)}\n`);

  // --- the report -----------------------------------------------------------
  for (const source of ["piece", "cache"] as const) {
    const judged = results.filter((r) => r.item.source === source);
    if (!judged.length) continue;
    const rate = (v: string) => judged.filter((r) => r.verdict.fits === v).length;
    console.log(
      `=== ${source === "piece" ? "piece glossaries (correctness)" : "gloss_cache (one frozen sense, met elsewhere)"} - ${judged.length} judged ===`,
    );
    console.log(
      `  correct ${rate("correct")}   wrong-sense ${rate("wrong-sense")}   wrong ${rate("wrong")}`,
    );
    for (const r of judged.filter((x) => x.verdict.fits !== "correct")) {
      console.log(
        `   ${r.verdict.fits === "wrong-sense" ? "s" : "!"} [${r.item.language}] "${r.item.word}" shown as "${r.item.meaning}"` +
          (r.item.spread > 1 ? `  (appears in ${r.item.spread} pieces)` : ""),
      );
      console.log(`     in: ${r.item.sentence.slice(0, 110)}`);
      console.log(`     should be: ${r.verdict.better} - ${r.verdict.note}`);
    }
    console.log("");
  }

  const cacheJudged = results.filter((r) => r.item.source === "cache");
  const stale = cacheJudged.filter((r) => r.verdict.fits === "wrong-sense").length;
  console.log(
    `${results.length} glosses judged. ` +
      (cacheJudged.length
        ? `Context-free cache misfits its context in ${stale}/${cacheJudged.length} sampled cases` +
          (stale === 0
            ? " - the frozen-sense worry does not fire at this sample size, and the cache can stay as it is."
            : " - that is the cost of keying the cache without context.")
        : ""),
  );
}

void main();
